---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  project: default
  sources:
  - repoURL: "https://grafana.github.io/helm-charts"
    chart: loki-stack
    targetRevision: 2.8.0
    helm:
      parameters:
      - name: "loki.rbac.pspEnabled"
        value: "false"
      - name: "grafana.rbac.pspEnabled"
        value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false